### ISSUE TITLE
please check the front page!!

### ISSUE THREAD

**Issue by babarbilal** [babarbilal/Mobile-E-commerce-website-add-to-cart-#12]
@ @khanshakeeb @MohibullahAnsari @fa15bs0058 @luqmaan96

**Comment by babarbilal** [comment]
screenshot  upload in a <>code  bar

**Comment by babarbilal** [comment]
now check online  http://mobileshop4u.move.pk/index.html  @MohibullahAnsari @khanshakeeb @fa15bs0058 @luqmaan96

**Comment by babarbilal** [comment]
only vivo mobile have a complete page.

**Comment by khanshakeeb** [comment]
@babarbilal you have done enough html, now need to build backend for the html templates. All products should come from DB

**Comment by babarbilal** [comment]
ok, sir now I am working on a DB.
