### ISSUE TITLE
blackberry specification issue

### ISSUE THREAD

**Issue by luqmaan96** [babarbilal/Mobile-E-commerce-website-add-to-cart-#4]
babar cant find the blackberry specification . 
we should skip that !

**Comment by khanshakeeb** [comment]
@luqmaan96  why we need blackberry specification? for what purpose?

**Comment by babarbilal** [comment]
because we want a data about phone to add data in my HTML because we using a shopping cart.Luqmaan only sends Samsung iPhone and LG data. thank you
